### ISSUE TITLE
Input lag in raw input mode (Windows 10)

### ISSUE THREAD

**Issue by dairin0d** [ColleagueRiley/RGFW#56]
On a Windows 10 PC, I ran into an odd behavior: when both mouse and keyboard are used simultaneously while `RGFW_window_mouseHold()` is active, and frame takes a sufficiently long time (e.g. over 30 ms), the `while (RGFW_window_checkEvent(win))` loop seems to exit before all events are actually processed, resulting in an accumulating "backlog" of events and manifesting as "lagging input".
I found that it could be mitigated by running the event processing loop twice per frame, but I think this is not actually supposed to happen. Most likely a Windows-specific issue, since it did not occur when testing on Linux.

Here's a small test-case program for easier reproduction of the quirk:
[main.txt](https://github.com/user-attachments/files/18202579/main.txt)

**Comment by ColleagueRiley** [comment]
@dairin0d Thank you for filing this issue.

> while RGFW_window_mouseHold() is active,

`RGFW_window_mouseHold` enables raw mouse input. This is probably a part of what's causing the problem, so it's important to note.

**Comment by ColleagueRiley** [comment]
@dairin0d I personally don't notice the lag. Could you possibly send a video?

**Comment by dairin0d** [comment]
@ColleagueRiley Sure! Here's my attempt at recording it:
https://github.com/user-attachments/assets/2a2a9699-9a42-48b8-9b3f-7e3794b28673

**Comment by ColleagueRiley** [comment]
@dairin0d Okay, I actually notice it on my system too. 

I think the problem might be raw input events also accepting raw key events. Then when raw key events are ignored, it also ignores regular key events. 

That's just a theory though and it might be wrong.

**Comment by ColleagueRiley** [comment]
@dairin0d I think I was wrong about the raw mouse events also accepting keyboard events. 

After looking into this issue I noticed a few problems:

1) Some mouse event inputs are sent to `WM_MOUSEMOVE`. X11 does something similar and what I have to do is handle both raw mouse events and regular mouse events ('translating' them to raw movement). 

2) There's a special case for handling mouse events that GLFW handles that I do not handle. 

I've updated RGFW to fix both of these problems, but I don't know if they fix this specific issue. (With this (https://github.com/ColleagueRiley/RGFW/commit/f2111d450d89fd4d0de574344d2811cf4bcd4454) commit)

Another problem I noticed is with the example code you sent. In your code you have the line.

```c
RGFW_sleep(50);
```

This is causing also causing event lag, because and is causing the FPS to be extremely low.

I would suggest you use something like

```c
RGFW_window_checkFPS(win, 60);
```

In order to wait enough time to slow the program to 60 FPS.

**Comment by dairin0d** [comment]
Sorry, got around to taking a look at it only now,
I tried to use the commit you mentioned, and the next after that, and also the current version of RGFW.h in the main branch. Unfortunately, not only do they not fix the original problem (the "backlog of events" still builds up), they also introduce additional weird behavior (I attached below an attempt to record it in my actual project), which seems to manifest as:
* sudden big jumps in camera zoom (zoom is controlled by mouse scroll, so normally one wheel tick would change the zoom by a fixed relative amount; but now one wheel tick seems to generate multiple scroll events, so zoom gets incremented many times in the same frame)
* "stubborn" camera insisting on returning to a certain angle (camera is controlled by mouse movement in raw input mode)
* the app "hanging" for a few seconds when attempting to close the window
* possibly other issues that I couldn't single out
I think it would be much better to revert those changes, since the original version seemed to work very well aside from the "event backlog" problem.
https://github.com/user-attachments/assets/a5c126ce-30db-465d-a418-7b5ff5726a3a
Since the project is a CPU-based octree renderer which can take 30 milliseconds on average to render one frame in that scene, the use of `RGFW_sleep(50)` in the test program was very much deliberate :-)

I decided to take a closer look at the Windows implementation of `RGFW_window_checkEvent()`, and I think I found the actual culprit of the problem I reported originally: in the `switch (msg.message)` statement, the `default` case (unrecognized/unsupported message type) sets `win->event.type` to 0, and further down the function returns NULL if `win->event.type` is 0. However, in this case it doesn't mean that the event queue has no messages left to process -- so in the case of unrecognized/unsupported message type, the `PeekMessageA()` should actually be reattempted again.
When I modified `RGFW_window_checkEvent()` like shown below, the "accumulating event backlog" indeed stopped from occurring:
```
peek_message:; // added line

if (PeekMessageA(&msg, win->src.window, 0u, 0u, PM_REMOVE)) {
    switch (msg.message) {
    ...
    default:
        win->event.type = 0;
        break;
    }

    TranslateMessage(&msg);
    DispatchMessageA(&msg);

    // If unsupported message type: message queue might not be exhausted yet, so we need to try peeking the next message
    if (win->event.type == 0) goto peek_message; // added line
}
```

Hope this would be of some help in solving the issue 🙂

**Comment by dairin0d** [comment]
An update: it turns out, the new problems with that commit (https://github.com/ColleagueRiley/RGFW/commit/f2111d450d89fd4d0de574344d2811cf4bcd4454) that I experienced were due to two reasons:
1. Mouse wheel sending multiple scroll events, and the app "hanging" for a few seconds upon pressing the "close" button, were caused by the line `const RAWINPUTDEVICE id = { 0x01, 0x02, 0, NULL };`. I got curious what RIDEV_REMOVE does, and it seems that it's required to actually stop receiving messages from an input device. When I reverted that line to the original version, those problems went away.
2. "Stubborn" camera behavior was caused by the changes in the `case WM_MOUSEMOVE:` block, which you have mostly reverted in the subsequent commit. so when I applied the same changes to my local version, camera stopped being "stubborn".

The rest of the changes in that commit do not appear to be causing any immediate problems, as far as I can tell from my limited use-case -- so it should be enough to leave the current version as-is, and just add back RIDEV_REMOVE and add proper handling of unrecognized messages. Sorry for getting a bit alarmist earlier 😅

**Comment by ColleagueRiley** [comment]
> add proper handling of unrecognized messages
What would you suggest for that?

**Comment by dairin0d** [comment]
I guess it would depend on your architectural preference for this library:
1. If you want `RGFW_window_checkEvent()` to always return either a valid event or NULL, then you'd need to use a loop of some sort, to peek messages until either a recognized one is encountered, or the message queue is empty.
2. If you want to prioritize users' ability to exit the event-checking loop as soon as they wish, you'd need to return non-NULL if the message was unrecognized. I.e., add a variable (for example, `is_unknown_message`) that gets set to true when encountering an unrecognized message (the `default` case), and in the end of `RGFW_window_checkEvent()` return `&win->event` if either `win->event.type` or `is_unknown_message` are non-zero. Since the users will likely be checking for specific event types anyway and ignoring the rest, encountering a "dummy" event with invalid type code (0) might not even get noticed.

Personally, I'd probably go with the 1st approach, since its behavior would look slightly less odd to the user, and its hypothetical weak point (encountering a sudden huge queue of unrecognized messages) is very unlikely to happen in practice.

**Comment by ColleagueRiley** [comment]
@dairin0d 
> then you'd need to use a loop of some sort, to peek messages until either a recognized one is encountered

This is pretty much what the switch already does. If there is no event NULL is returned. If there is an unrecognized event, it would run the function again, making is so it loops until there is a recognized event or no events.

**Comment by dairin0d** [comment]
Oops! Sorry, didn't notice the commit https://github.com/ColleagueRiley/RGFW/commit/e0830f5f362d29cc1734fc3d09efa3b5a1d525d2 you made around the time I was writing the last message, which solves the issue via recursion.

I downloaded the current version of RGFW.h from the main branch and ran into a compilation error (it complains about the line `return &win->event.type;` returning a wrong type, which was introduced in the commit https://github.com/ColleagueRiley/RGFW/commit/57ced279a7261e411098de1ef16dc876dba26b6d).
I locally fixed it by removing the `.type` at the end, and after that my program compiled and did not appear to have any problems on Windows. Technically, this issue can now be closed, though I'd prefer to do it once the compilation error is fixed too :-)

**Comment by ColleagueRiley** [comment]
Oops, I'm not sure why this didn't send an error to me when I tested it.. Everything should be fixed now! Thanks for filing these issues!

**Comment by dairin0d** [comment]
Indeed, everything now works as expected. Glad to be of help!
